//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AAcostaAeroMexicoEntities : DbContext
    {
        public AAcostaAeroMexicoEntities()
            : base("name=AAcostaAeroMexicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pasajero> Pasajeroes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Vuelo> Vueloes { get; set; }
        public virtual DbSet<ViajePasajero> ViajePasajeroes { get; set; }
    
        public virtual int PasajeroAdd(string nombre, string apellidos)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PasajeroAdd", nombreParameter, apellidosParameter);
        }
    
        public virtual ObjectResult<PasajeroGetAll_Result> PasajeroGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PasajeroGetAll_Result>("PasajeroGetAll");
        }
    
        public virtual int VueloAdd(string fechaInicio, string numeroDeVuelo, string origen, string destino, string fechaDeSalida, string fechaFin)
        {
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var numeroDeVueloParameter = numeroDeVuelo != null ?
                new ObjectParameter("NumeroDeVuelo", numeroDeVuelo) :
                new ObjectParameter("NumeroDeVuelo", typeof(string));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            var fechaDeSalidaParameter = fechaDeSalida != null ?
                new ObjectParameter("FechaDeSalida", fechaDeSalida) :
                new ObjectParameter("FechaDeSalida", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VueloAdd", fechaInicioParameter, numeroDeVueloParameter, origenParameter, destinoParameter, fechaDeSalidaParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<VueloGetAll_Result> VueloGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VueloGetAll_Result>("VueloGetAll");
        }
    
        public virtual ObjectResult<UsuarioGetByUserName_Result> UsuarioGetByUserName(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioGetByUserName_Result>("UsuarioGetByUserName", userNameParameter);
        }
    
        public virtual int ViajePasajeroAdd(Nullable<int> idViaje, Nullable<int> idPasajero)
        {
            var idViajeParameter = idViaje.HasValue ?
                new ObjectParameter("IdViaje", idViaje) :
                new ObjectParameter("IdViaje", typeof(int));
    
            var idPasajeroParameter = idPasajero.HasValue ?
                new ObjectParameter("IdPasajero", idPasajero) :
                new ObjectParameter("IdPasajero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ViajePasajeroAdd", idViajeParameter, idPasajeroParameter);
        }
    
        public virtual ObjectResult<ViajePasajeroGetAll_Result> ViajePasajeroGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViajePasajeroGetAll_Result>("ViajePasajeroGetAll");
        }
    }
}
